#pragma once

/*
* FIRST TWO BYTES OF EVERY PACKET ARE THE COMMAND ID
* PAYLOAD FOLLOWS IMMEDIATELY AFTER
*/

#define LEDS_OFF 0x0eaf
/*  CLEAR STRIP
* PAYLOAD[0] STRIP TO SELECT
* PAYLOAD[1...] UNUSED
*/
#define LEDS_ON 0x915b
/*  RESUME ANIMATING IF PAUSED
* PAYLOAD[0] STRIP TO SELECT
* PAYLOAD[1...] UNUSED
*/
#define IDLE_ANIMATE 0xa146
/*  RUN PURPLE/GREEN IDLE ANIMATION
* PAYLOAD[0] STRIP TO SELECT
* PAYLOAD[1] SWAPS
* PAYLOAD[2] START GREEN
* PAYLOAD[3...] UNUSED
*/
#define CREATE_STRIP 0x8bda
/*  COMMAND TO CREATE NEW LED CONTROLLER
* PAYLOAD[0] PIN OF STRIP
* PAYLOAD[1] LENGTH OF STRIP
* PAYLOAD[2...] UNUSED
*/
#define DESTROY_STRIP 0x10e7
/*  COMMAND TO DESTROY LED CONTROLLER
* PAYLOAD[0] ID OF STRIP
* PAYLOAD[1...] UNUSED
*/
